//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telefon_Rehberi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Calisanlar
    {
        public int CalisanId { get; set; }
        [Required(ErrorMessage ="Bu Alan Zorunludur",AllowEmptyStrings =false)]
        public string Adi { get; set; }
        [Required(ErrorMessage = "Bu Alan Zorunludur", AllowEmptyStrings = false)]
        public string Soyadi { get; set; }
        [Required(ErrorMessage = "Bu Alan Zorunludur", AllowEmptyStrings = false)]
        public string Telefon { get; set; }
        public int DepartmanID { get; set; }
        public int YöneticiID { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual YöneticiBilgileri YöneticiBilgileri { get; set; }
    }
}
